### ISSUE TITLE
change items

### ISSUE THREAD

**Issue by Azaroth90340** [InfinityGamers/Weapons#1]
Hello ,

Already congratulated for your plugin which is great, I would like to know which line should I change to replace the armor in horseshoe, by another items, because I would like to create several weapons with texture packs, but I would like to replace the weapons by several items?

Thank you for your reply .

**Comment by Azaroth90340** [comment]
and one more question, how can I make my gun do no damage to the lobby because I have disabled pvp and damage, but players can still kill themselves?

**Comment by xBeastMode** [comment]
Pls refer to #2 for updates.
