### ISSUE TITLE
[Suggestion] Rockets

### ISSUE THREAD

**Issue by KadTheHunter** [InfinityGamers/Weapons#10]
There should be separate ammo for Rockets, that way players can have:
1 Panzerfaust, 10 Rockets
1 Gun, 64 Ammo

and the Rockets and Ammo cant be confused, stacked, etc.

**Comment by jennocool** [comment]
Lol I was gonne say that in an issue do you already know an solution

**Comment by KadTheHunter** [comment]
oof, forgot I even made this issue. Due to lack of response from Dev, I should honestly close it, but I'll leave it open just in case they ever work on it.

**Comment by jennocool** [comment]
I think I found a  solution use the plugin explosivearrow on poggit

**Comment by xBeastMode** [comment]
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.
