### ISSUE TITLE
no weapon can be used

### ISSUE THREAD

**Issue by ladenlearnp** [InfinityGamers/Weapons#11]
Hello, I can use “/weapon guns list” and see then 
“mg42, mp40, minigun,thompson,m1911, panzerfaust”
but I cannot use the weapons. With “/weapon gun [player] give” or “/weapon gun [player]” I don’t get a weapon. What am I doing wrong?

**Comment by ladenlearnp** [comment]
Hi, additional: If i use /weapon ammo [player] I see "Internal server error". The server  crashes. I use pocketmine 1.14.1

**Comment by xBeastMode** [comment]
you gotta add gun/amount before player, use /weapons gun <gun name> [player] or  /weapons gun <ammo amount> [player]
