### ISSUE TITLE
No Damage at entities (pureEntetiesX/VanillaEntityAPI)

### ISSUE THREAD

**Issue by DemonicDev** [InfinityGamers/Weapons#18]
It is an realy good and funny plugin. Could you make the plugin pureEntetiesX compatible ? that would make me and my friends Happy (^-^).

**Comment by xBeastMode** [comment]
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.

**Comment by DemonicDev** [comment]
I wrote once my own plugin, cuz urs inspired me so much :> i will uploaded in future :D

**Comment by xBeastMode** [comment]
Nice, upload it yes :)
