### ISSUE TITLE
Panzerfaust Explosion

### ISSUE THREAD

**Issue by KadTheHunter** [InfinityGamers/Weapons#2]
Is there a way to make the Panzerfaust destroy blocks (and even better, a way to enable/disable that via a config?)

Also, as #1 says, the items should be changed (Iron shovels maybe)

**Comment by benda95280** [comment]
Has i can see in code, it seems to do it ? (Explode with block destruction)

**Comment by KadTheHunter** [comment]
@benda95280 as far as I've tested, it doesn't explode blocks. It does the explosion graphics as if TNT was exploded, and it deals damage to players in the blast radius, but so far I haven't been able to make it destroy blocks. I'll test more this afternoon, but I'll probably end up editing CobaltGuns and using it.

**EDIT:** No, it doesn't explode blocks. I tested all over the map, on different blocks, etc., nothing was destroyed. The explosion graphic and sound played, but that was it.

**Comment by benda95280** [comment]
Strange, was thinking it because this line:
https://github.com/InfinityGamers/Weapons/blob/69b5c9d3fe8eb954677f74ffb3233b79c5f6da6e/src/xBeastMode/Weapons/BulletEntity.php#L28

Explosion::explodeA() performs an explosion with no terrain alteration, whereas Explosion::explodeB() alters the terrain.

Are you sur you'r using lastest version, edit was made 25 days ago.

**Comment by LegoFan48737** [comment]
Im using the public Poggit version, I'll double check when I downloaded it.

**Comment by KadTheHunter** [comment]
Oops, button mixup 🤦

**Comment by KadTheHunter** [comment]
@benda95280 I downloaded it on September 21st, which is after that update. Could be that update was *disabling* block damage.

**Comment by KadTheHunter** [comment]
@benda95280 correction, [this](https://forums.pmmp.io/threads/explosions-does-not-work.5549/) explains how you need both `$explosion->explodeA()` and `$explosion->explodeB()` to make the explosion break blocks. A calculates the blocks, B does the explosion. A on its own calculates but does no explosion, B on itself does the explosion but doesn't break blocks.

@xBeastMode any thoughts on if this is correct, and if so, if it will be added here?

**Comment by benda95280** [comment]
If no news from xBeastMode, i can try to do some modification with your last information to test it and maybe do a PR.

**Comment by benda95280** [comment]
PR done #3

**Comment by KadTheHunter** [comment]
Thanks, I'll try it out today! Hopefully this works 😄

**Comment by KadTheHunter** [comment]
@benda95280 It works!!! Just tested on my server and it works perfectly. Hopefully Beast will accept the PR and make it official. Thank you so much for helping with this, it's a major part of what my Anarchy server is going to have.

**Comment by benda95280** [comment]
No problem, i like this plugin, there is so much possibilities.
I'll be happy to exchange some words with the dev :)

**Comment by xBeastMode** [comment]
Hey guys. So this plugin was merely for experimental/fun purposes. Once I'm free I will try to push an update for customizable weapons with things such as: custom item id, damage, pitch, explosion, etc.

**Comment by KadTheHunter** [comment]
Ok sounds great. Looking forward to it!

**Comment by xBeastMode** [comment]
There ya go https://poggit.pmmp.io/r/67080/Weapons_dev-4.phar 😄
