### ISSUE TITLE
not an issue but more like a help

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/Weapons#4]
i have an idea to mix this plugin with another plugin, im trying to make a free for all game like call of duty using this gun plugin, is there a way to make the plugin give the player a gun and ammo via an other plugin except by using DispatchCommand ? like instead of making the plugin run the command for the player i want it to directly give it to him

**Comment by ghost** [comment]
just realised there is no death announced and therefore damager can't be known so this plugin won't work with another plugin cuz the other plugin will try to know the damager then it will crash.

**Comment by KadTheHunter** [comment]
This is actually related to my question in #6 
I was curious how you can use /give, or use a plugin to set it into a chest.
