### ISSUE TITLE
[Question] Item names

### ISSUE THREAD

**Issue by KadTheHunter** [InfinityGamers/Weapons#6]
In addition to IDs, how does the plugin tell the difference between each weapon, and more importantly, what name or other identifier do I need to add the weapons into chests remotely? Working on a core for my server, and just realized I can add the item itself, but merely the item, not said item as a gun.

**Comment by KadTheHunter** [comment]
@xBeastMode I suppose to be more specific, what I'm asking is, if I were to use /give, or have a plugin create the gun and stick it in a chest, what do I need to do to get it as a gun, and not as a normal item? Just the name? or something else?

**Comment by KadTheHunter** [comment]
.....at this point, is anyone capable of even giving any sort of answer? I've looked through the code itself, but I still can't make sense of how I could use /give, or use the Console to fill a chest with the Guns, as Item ID alone doesn't work.

**Comment by benda95280** [comment]
From what i see, you need NBT data too, for the type of gun.
Sorry, no time to check it.

**Comment by KadTheHunter** [comment]
Well, I've bypassed the issue by using EasyKits by Andreas instead of setting guns in chests around the map, still curious what is needed though, so leaving this issue open in the hope @xBeastMode can help.

**Comment by KadTheHunter** [comment]
This may help
https://forums.pmmp.io/threads/getting-the-killer-when-its-death-by-custom-projectile.8720/#post-67348

**Comment by xBeastMode** [comment]
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.
