### ISSUE TITLE
[Suggestion] Grenades

### ISSUE THREAD

**Issue by KadTheHunter** [InfinityGamers/Weapons#7]
It would be pretty cool if you could use either Eggs, or TNT to make a grenade, that detonates at maybe 2 seconds after throwing it. Not sure how it would work with TNT as you would need to make that throwable, but you could probably do it pretty easy with the Egg.

**Comment by xBeastMode** [comment]
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.
