### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by nghiaomgvn** [InfinityGamers/Weapons#8]
Can you allow the console to use plugins?

**Comment by Lycol50** [comment]
If you have PurePerms installed, simply edit the groups.yml (~/plugin_data/pureperms) and add the permission mentioned on plugin.yml of this repo (https://github.com/InfinityGamers/Weapons/blob/master/plugin.yml)

**Comment by Lycol50** [comment]
If you have PurePerms installed, simply edit the groups.yml (~/plugin_data/pureperms) and add the permission mentioned on  of this repo

**Comment by xBeastMode** [comment]
This is an experimental plugin, it is not meant to be used in production servers. Most of my open source work is experiemental and I don't plan on updating it any longer.
